apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-container
        image: 369801643157.dkr.ecr.us-west-1.amazonaws.com/esquire-ecr:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8085

# Service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-app
  name: hello-service
  namespace: qa
spec:
  ports:
  - name: http
    port: 8085
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: hello-app
